# Generated by Django 5.1.7 on 2025-03-31 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_budget_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='created_at',
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
