# Generated by Django 5.1.7 on 2025-03-31 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_remove_budget_created_at_expense_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
