# Generated by Django 5.1.7 on 2025-04-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_delete_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='travel_mode',
            field=models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight')], default='car', max_length=10),
        ),
    ]
