# Generated by Django 5.1.7 on 2025-04-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_itinerary_travel_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='destinations',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destinations',
            field=models.ManyToManyField(related_name='itineraries', to='itineraries.destination'),
        ),
    ]
