# Generated by Django 5.1.7 on 2025-04-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_remove_itinerary_destinations_itinerary_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('travel_mode', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight')], default='car', max_length=10)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinations', models.ManyToManyField(related_name='suggested_itineraries', to='itineraries.destination')),
            ],
        ),
    ]
