# Generated by Django 5.1.7 on 2025-04-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0010_remove_suggesteditinerary_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='destinations',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destinations',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
